# Use Node.js as base image
FROM node:23

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the service runs on
EXPOSE 4002

# Command to run the service
CMD ["node", "server.js"]
